# Generated by Django 4.1.3 on 2022-11-29 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AFMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('af_name', models.CharField(max_length=200)),
                ('original_af_id', models.PositiveIntegerField(unique=True)),
                ('original_af_tags', models.JSONField(default=dict)),
                ('nlp_tags', models.JSONField(default=dict)),
                ('is_mapped_manually', models.BooleanField()),
                ('extra', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('url', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('extra_info', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToFetchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('original_project_id', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('not_fetched', 'Not Fetched'), ('fetching', 'Fetching'), ('fetched', 'Fetched'), ('errored', 'Errored'), ('not_found', 'Not Found')], default='not_fetched', max_length=20)),
                ('last_fetched_lead_created_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetched_entry_created_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('original_project_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra', models.JSONField(default=dict)),
                ('af_mapping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.afmapping')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_fetch_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tofetchproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('original_organization_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=50)),
                ('extra', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('original_lead_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('extraction_status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (4, 'Retrying'), (2, 'Success'), (3, 'Failed')], default=0)),
                ('text_extract', models.TextField(blank=True, null=True)),
                ('confidentiality', models.CharField(choices=[('unprotected', 'Public'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='unprotected', max_length=30)),
                ('source_url', models.TextField()),
                ('extra', models.JSONField(default=dict)),
                ('authoring_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_leads', to='core.organization')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('publishing_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_leads', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('original_entry_id', models.PositiveIntegerField(unique=True)),
                ('original_lang', models.CharField(max_length=50)),
                ('excerpt_en', models.TextField()),
                ('excerpt_es', models.TextField()),
                ('excerpt_fr', models.TextField()),
                ('excerpt_pt', models.TextField()),
                ('original_af_tags', models.JSONField(default=dict)),
                ('nlp_af_tags', models.JSONField(default=dict)),
                ('export_data', models.JSONField(default=dict)),
                ('af_exportable_data', models.JSONField(default=dict)),
                ('extra', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeepDataFetchTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('last_fetched_org_created_at', models.DateTimeField(null=True)),
                ('last_fetched_af_created_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassificationPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('original_en_predictions', models.JSONField(default=dict)),
                ('original_es_predictions', models.JSONField(default=dict)),
                ('original_fr_predictions', models.JSONField(default=dict)),
                ('original_pt_predictions', models.JSONField(default=dict)),
                ('nlp_en_predictions', models.JSONField(default=dict)),
                ('nlp_es_predictions', models.JSONField(default=dict)),
                ('nlp_fr_predictions', models.JSONField(default=dict)),
                ('nlp_pt_predictions', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entry')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classificationmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
