# Generated by Django 4.1.3 on 2022-11-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepdatafetchtracker',
            old_name='last_fetched_af_created',
            new_name='last_fetched_af_created_at',
        ),
        migrations.RenameField(
            model_name='deepdatafetchtracker',
            old_name='last_fetched_org_created',
            new_name='last_fetched_org_created_at',
        ),
        migrations.RemoveField(
            model_name='deepdatafetchtracker',
            name='last_fetched_af_id',
        ),
        migrations.RemoveField(
            model_name='deepdatafetchtracker',
            name='last_fetched_org_id',
        ),
    ]
