# Generated by Django 4.1.3 on 2022-11-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_last_fetched_af_created_deepdatafetchtracker_last_fetched_af_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tofetchproject',
            old_name='last_fetched_entry_created',
            new_name='last_fetched_entry_created_at',
        ),
        migrations.RenameField(
            model_name='tofetchproject',
            old_name='last_fetched_lead_created',
            new_name='last_fetched_lead_created_at',
        ),
        migrations.RemoveField(
            model_name='tofetchproject',
            name='last_fetched_entry_id',
        ),
        migrations.RemoveField(
            model_name='tofetchproject',
            name='last_fetched_lead_id',
        ),
    ]
