# Generated by Django 4.1.3 on 2023-02-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tofetchproject_is_added_manually_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classificationmodel',
            name='extra_info',
        ),
        migrations.AddField(
            model_name='classificationpredictions',
            name='embeddings',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.entry'),
        ),
    ]
