# Generated by Django 4.1.3 on 2023-02-21 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_classificationmodel_extra_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="embeddings",
        ),
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="nlp_es_predictions",
        ),
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="nlp_fr_predictions",
        ),
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="nlp_pt_predictions",
        ),
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="original_en_predictions",
        ),
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="original_es_predictions",
        ),
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="original_fr_predictions",
        ),
        migrations.RemoveField(
            model_name="classificationpredictions",
            name="original_pt_predictions",
        ),
    ]
