# Generated by Django 4.1.3 on 2022-11-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_last_fetched_entry_created_tofetchproject_last_fetched_entry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='to_fetch_project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.tofetchproject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='af_mapping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.afmapping'),
        ),
    ]
