# Generated by Django 4.1.3 on 2022-11-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_to_fetch_project_alter_project_af_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='exportdata',
            new_name='af_exportable_data',
        ),
        migrations.AddField(
            model_name='entry',
            name='export_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tofetchproject',
            name='last_fetched_entry_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tofetchproject',
            name='last_fetched_lead_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
