# Generated by Django 4.1.3 on 2023-02-21 09:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_classificationpredictions_embeddings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationpredictions",
            name="embeddings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(blank=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="deepdatafetchtracker",
            name="last_fetched_af_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deepdatafetchtracker",
            name="last_fetched_org_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
