# Generated by Django 4.1.3 on 2023-02-21 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_classificationpredictions_embeddings_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="excerpt_es",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="excerpt_fr",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="excerpt_pt",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="nlp_af_tags",
        ),
    ]
