# Generated by Django 4.1.7 on 2023-03-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_computedfeaturedrift_entry_count'),
        ('core', '0005_tofetchproject_active_status'),
    ]

    operations = [
    ]
