# Generated by Django 4.1.3 on 2022-11-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_exportdata_entry_af_exportable_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='extraction_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (4, 'Retrying'), (2, 'Success'), (3, 'Failed')], default=0),
        ),
    ]
