# Generated by Django 4.1.7 on 2023-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20230321_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedfeaturedrift',
            name='entry_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
