# Generated by Django 4.1.7 on 2023-03-29 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_computedfeaturedrift_entry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='deep_entry_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computedfeaturedrift',
            name='entry_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
