# Generated by Django 4.1.3 on 2023-02-22 05:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_entry_excerpt_es_remove_entry_excerpt_fr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classificationpredictions",
            name="embeddings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(blank=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
