# Generated by Django 4.1.3 on 2022-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lead_extraction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='text_extract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
