# Generated by Django 4.1.3 on 2022-11-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tofetchproject_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeadVectorsNLP',
        ),
    ]
