# Generated by Django 4.1.7 on 2023-02-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_classificationpredictions_nlp_en_predictions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProjectPerfMatrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, max_length=250)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1score', models.FloatField(blank=True, null=True)),
                ('support', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryWiseMatchRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectors_completely_matched', models.FloatField(blank=True, null=True)),
                ('sectors_missing', models.FloatField(blank=True, null=True)),
                ('sectors_wrong', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_completely_matched', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_missing', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_wrong', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_completely_matched', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_missing', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_wrong', models.FloatField(blank=True, null=True)),
                ('entry_id', models.PositiveIntegerField()),
                ('project_id', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWiseMatchRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.PositiveIntegerField()),
                ('sectors_completely_matched_mean', models.FloatField(blank=True, null=True)),
                ('sectors_missing_mean', models.FloatField(blank=True, null=True)),
                ('sectors_wrong_mean', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_completely_matched_mean', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_missing_mean', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_wrong_mean', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_completely_matched_mean', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_missing_mean', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_wrong_mean', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectWisePerfMatrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.PositiveIntegerField()),
                ('sectors_f1score', models.FloatField(blank=True, null=True)),
                ('sectors_precision', models.FloatField(blank=True, null=True)),
                ('sectors_recall', models.FloatField(blank=True, null=True)),
                ('sectors_support', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_f1score', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_precision', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_recall', models.FloatField(blank=True, null=True)),
                ('subpillars_1d_support', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_f1score', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_precision', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_recall', models.FloatField(blank=True, null=True)),
                ('subpillars_2d_support', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TagWisePerfMatrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1score', models.FloatField(blank=True, null=True)),
                ('support', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField()),
            ],
        ),
    ]
