# Generated by Django 4.1.7 on 2023-05-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_failedcallback_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlprequest',
            name='type',
            field=models.CharField(choices=[('ngrams', 'Ngrams'), ('topicmodel', 'Topicmodel'), ('summarization', 'Summarization'), ('geolocation', 'Geolocation'), ('tags-mapping', 'Tags Mapping'), ('entry-classification', 'Entry Classification')], max_length=20),
        ),
    ]
