# Generated by Django 4.1.7 on 2023-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_allprojectperfmatrics_categorywisematchratios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_project_id', models.PositiveIntegerField()),
                ('current_project_id', models.PositiveIntegerField()),
                ('reference_dataset_len', models.PositiveIntegerField(blank=True, null=True)),
                ('current_dataset_len', models.PositiveIntegerField(blank=True, null=True)),
                ('drift_share', models.BooleanField()),
                ('number_of_columns', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_drifted_columns', models.PositiveIntegerField(blank=True, null=True)),
                ('share_of_drifted_columns', models.FloatField(blank=True, null=True)),
                ('dataset_drift', models.BooleanField()),
                ('generated_at', models.DateTimeField()),
            ],
        ),
    ]
