# Generated by Django 4.1.7 on 2023-05-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_failedcallback_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='nlprequest',
            name='last_process_attempted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='nlprequest',
            name='process_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nlprequest',
            name='type',
            field=models.CharField(choices=[('ngrams', 'Ngrams'), ('topicmodel', 'Topicmodel'), ('summarization', 'Summarization'), ('summarization-v2', 'Summarization-V2'), ('geolocation', 'Geolocation'), ('tags-mapping', 'Tags Mapping'), ('entry-classification', 'Entry Classification')], max_length=20),
        ),
    ]
