# Generated by Django 4.1.7 on 2023-05-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_nlprequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlprequest',
            name='type',
            field=models.CharField(choices=[('ngrams', 'Ngrams'), ('topicmodel', 'Topicmodel'), ('summarization', 'Summarization'), ('summarization-v2', 'Summarization-V2'), ('geolocation', 'Geolocation'), ('tags-mapping', 'Tags Mapping'), ('entry-classification', 'Entry Classification')], max_length=20),
        ),
    ]
