# Generated by Django 4.1.7 on 2023-03-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_featuredrift_computedfeaturedrift"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classificationmodel",
            old_name="url",
            new_name="reference_train_data",
        ),
        migrations.AddField(
            model_name="classificationmodel",
            name="model_uri",
            field=models.TextField(blank=True, null=True),
        ),
    ]
