# Generated by Django 4.1.7 on 2023-07-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_nlprequest_result_s3_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='nlp_mapping',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='entry',
            name='nlp_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='entry',
            name='af_exportable_data',
            field=models.JSONField(default=list),
        ),
    ]
