# Generated by Django 4.2.3 on 2023-07-20 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entry_nlp_mapping_entry_nlp_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationpredictions',
            name='affected_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='age',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='gender',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='severity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='specific_needs_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='subpillars_1d',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='classificationpredictions',
            name='subpillars_2d',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=list, size=None),
        ),
    ]
