# Generated by Django 4.2.3 on 2023-07-21 06:07

from django.db import migrations


def delete_items(apps, schema_editor):
    ToFetchProject = apps.get_model('core', 'ToFetchProject')
    # Delete existing projects/leads/entries related data.
    # Deleting ToFetchProject will do this due to cascading
    ToFetchProject.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_entry_af_exportable_data_entry_nlp_mapping_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_items)
    ]
