# Generated by Django 4.2.3 on 2023-08-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230721_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allprojectperfmetrics',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='projectwiseperfmetrics',
            name='sectors_support',
        ),
        migrations.RemoveField(
            model_name='projectwiseperfmetrics',
            name='subpillars_1d_support',
        ),
        migrations.RemoveField(
            model_name='projectwiseperfmetrics',
            name='subpillars_2d_support',
        ),
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='f1score',
        ),
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='recall',
        ),
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='support',
        ),
    ]
