# Generated by Django 4.2.3 on 2023-08-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230721_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='f1score',
        ),
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='precision',
        ),
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='recall',
        ),
        migrations.RemoveField(
            model_name='tagwiseperfmetrics',
            name='support',
        ),
        migrations.AddField(
            model_name='tagwiseperfmetrics',
            name='metrics',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tagwiseperfmetrics',
            name='scores',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
