# Generated by Django 4.2.3 on 2023-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_allprojectperfmetrics_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojectperfmetrics',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='affected_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='affected_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='affected_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='age_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='age_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='age_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='displaced_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='displaced_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='displaced_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='gender_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='gender_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='gender_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='non_displaced_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='non_displaced_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='non_displaced_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='pillars_1d_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='pillars_1d_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='pillars_1d_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='pillars_2d_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='pillars_2d_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='pillars_2d_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='severity_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='severity_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='severity_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='specific_needs_groups_f1score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='specific_needs_groups_precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectwiseperfmetrics',
            name='specific_needs_groups_recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagwiseperfmetrics',
            name='metric',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tagwiseperfmetrics',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
