# Generated by Django 4.2.3 on 2023-08-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_tagwiseperfmetrics_f1score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allprojectperfmetrics',
            old_name='categories',
            new_name='category',
        ),
    ]
