# Generated by Django 4.2.3 on 2023-08-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projectwiseperfmetrics_affected_f1score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectwiseperfmetrics',
            name='sectors_support',
        ),
        migrations.RemoveField(
            model_name='projectwiseperfmetrics',
            name='subpillars_1d_support',
        ),
        migrations.RemoveField(
            model_name='projectwiseperfmetrics',
            name='subpillars_2d_support',
        ),
    ]
