# Generated by Django 4.2.3 on 2023-11-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_categorywisematchratios_affected_completely_matched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlprequest',
            name='type',
            field=models.CharField(choices=[('ngrams', 'Ngrams'), ('topicmodel', 'Topicmodel'), ('summarization', 'Summarization'), ('summarization-v2', 'Summarization-V2'), ('geolocation', 'Geolocation'), ('tags-mapping', 'Tags Mapping'), ('entry-classification', 'Entry Classification'), ('text-extraction', 'Text Extraction'), ('entry-extraction-classification', 'Entry Extraction Classification')], max_length=50),
        ),
    ]
