# Generated by Django 4.1.7 on 2023-03-21 06:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModuleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Initiated'), (2, 'Success'), (3, 'Failed')], default=1)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('result_s3_link', models.URLField()),
                ('type', models.CharField(choices=[('ngrams', 'Ngrams'), ('topicmodel', 'Topicmodel'), ('summarization', 'Summarization')], max_length=20)),
            ],
            options={
                'db_table': 'event_status_tracker',
            },
        ),
    ]
