# Generated by Django 4.1.7 on 2023-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_module', '0002_analysismodulerequest_request_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodulerequest',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysismodulerequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initiated'), (2, 'Success'), (3, 'Failed'), (4, 'Process Input Url Failed')], default=1),
        ),
    ]
