# Generated by Django 4.1.7 on 2023-04-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_module', '0005_alter_analysismodulerequest_result_s3_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismodulerequest',
            name='type',
            field=models.CharField(choices=[('ngrams', 'Ngrams'), ('topicmodel', 'Topicmodel'), ('summarization', 'Summarization'), ('geolocation', 'Geolocation')], max_length=20),
        ),
    ]
