# Generated by Django 4.1.7 on 2023-04-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_module', '0006_alter_analysismodulerequest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismodulerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysismodulerequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysismodulerequest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='FailedCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('request_unique_id', models.UUIDField(unique=True)),
                ('retries_count', models.PositiveIntegerField(default=0)),
                ('last_retried_at', models.DateTimeField(null=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'Success'), (1, 'Retries maxed out'), (2, 'Failed'), (3, 'Retrying')], default=3)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'failed_callback_tracker',
            },
        ),
    ]
