# Generated by Django 4.1.7 on 2023-05-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_module', '0007_analysismodulerequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedcallback',
            name='created_by',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AnalysisModuleRequest',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='FailedCallback',
                ),
            ],
            database_operations=[],
        )
    ]
