# Generated by Django 4.1.3 on 2022-11-23 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_delete_leadvectorsnlp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LSHIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('created', 'Created')], default='creating', max_length=20)),
                ('index_url', models.TextField(blank=True, null=True)),
                ('encoding_type', models.CharField(choices=[('glove_6b_300', 'Glove 6B 300d'), ('glove_840b_300', 'Glove 840B 300d'), ('lsh_256_perms', 'LSH 256 Perms'), ('lsh_128_perms', 'LSH 128 Perms')], max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'unique_together': {('project', 'encoding_type')},
            },
        ),
        migrations.CreateModel(
            name='LeadVectorsNLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('encoding_type', models.CharField(choices=[('glove_6b_300', 'Glove 6B 300d'), ('glove_840b_300', 'Glove 840B 300d'), ('lsh_256_perms', 'LSH 256 Perms'), ('lsh_128_perms', 'LSH 128 Perms')], max_length=50)),
                ('encoding', models.JSONField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
                ('lsh_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deduplication.lshindex')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
