# Generated by Django 4.1.3 on 2022-11-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_delete_leadvectorsnlp'),
        ('deduplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('lead_hash', models.BinaryField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.lead')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='lshindex',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lshindex',
            name='index_pickle',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='lshindex',
            name='pickle_version',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lshindex',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.DeleteModel(
            name='LeadVectorsNLP',
        ),
        migrations.AddField(
            model_name='leadhash',
            name='lsh_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deduplication.lshindex'),
        ),
        migrations.RemoveField(
            model_name='lshindex',
            name='encoding_type',
        ),
        migrations.RemoveField(
            model_name='lshindex',
            name='index_url',
        ),
        migrations.AlterUniqueTogether(
            name='leadhash',
            unique_together={('lead', 'lsh_index')},
        ),
    ]
