# Generated by Django 4.1.3 on 2022-12-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduplication', '0002_deduplicationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadhash',
            options={'verbose_name_plural': 'Lead Hashes'},
        ),
        migrations.AlterModelOptions(
            name='lshindex',
            options={'verbose_name_plural': 'LSH Indices'},
        ),
        migrations.AlterField(
            model_name='deduplicationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deduplicationrequest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leadhash',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leadhash',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lshindex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lshindex',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
