# Generated by Django 4.1.3 on 2022-12-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduplication', '0003_alter_leadhash_options_alter_lshindex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lshindex',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lshindex',
            name='has_errored',
            field=models.BooleanField(default=False),
        ),
    ]
