# Generated by Django 4.1.3 on 2022-12-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deduplication', '0004_lshindex_error_lshindex_has_errored'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduplicationrequest',
            name='client_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
